Basic dockerfile and instructions to execute
jwhitcraft/rome pull request #1
Opened 2017-01-23 04:54 UTC by sadekbaroudi

2017-01-23 12:42 UTC, jwhitcraft requested changes
See Comments :P

2017-01-23 12:42 UTC, jwhitcraft commented on README.md
> +docker build -t registry.sugarcrm.net/rome:1.0.0 .
lets put it here,

`registry.sugarcrm.net/engineering/rome:latest`

and this is v2.0.0Alpha for now since 1.0 exists in the Mango repo.

2017-01-27 07:09 UTC, sadekbaroudi commented on README.md
> +docker build -t registry.sugarcrm.net/rome:1.0.0 .
Updated to latest!

2017-01-27 07:10 UTC, sadekbaroudi commented
Resolved!

2017-01-27 14:15 UTC, jwhitcraft approved these changes
Approved :shipit: :goat:

2017-01-27 14:15 UTC, merged